<a href="https://colab.research.google.com/github/mriyas123/Pandas_GuviTasks/blob/main/Numpy_Test_%26_Chi_squared_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## #NUMPY TEST

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
x=np.arange(1,11)
x1=x+1
print(x1)

[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
m, n = 10,10
A = np.empty(shape=(m, n), dtype=int)

i, j = np.ogrid[:m, :n]
#print(i,j)
A = i+j

print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [ ]:
a = np.zeros((2, 512*512), dtype=np.float32)  
a[1, :] = 1.0  
a[0, :] = 0.1  
print(a)

[[0.1 0.1 0.1 ... 0.1 0.1 0.1]
 [1.  1.  1.  ... 1.  1.  1. ]]


In [ ]:
import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
b=np.std(data,axis=1)
print(b)
c=np.mean(data,axis=1)
print("mean = ",c)

[ 1.37278313  1.23728069  1.20619632  1.43406147  1.0135916   1.22386547
 16.29993575 10.16555932  0.49073632  2.82230076  4.37834506  2.32500901
  0.72034385  0.71898142  9.65449262  2.1897444   9.69876766  1.11937805
  0.80095222  4.19681396  1.88496703  0.62990618  0.8064708   0.47059013
  0.5757512   1.91579699  0.50669591  0.7897075   2.25315162  1.78368755
  3.79475555  1.25421529  0.1194862   3.3193863   4.41180438  0.69643876
  1.48047503  8.13596053  1.23323293  2.3990874   3.42906516  0.57129252
  2.08383488  0.71831452  0.7566149   1.9717655   0.79822339  0.65340284
  0.79465579  4.40346505]
mean =  [ 1.82134207  1.12363846  1.49497132  1.6092419   1.13527748  1.15835114
 10.01022025  5.54068944  0.6377501   2.48272917  4.44980569  2.75160229
  0.93893959  1.64285876  7.14792147  1.78702584  6.55242248  1.50476289
  1.36910811  2.52358007  2.06355211  0.96521343  0.98188535  1.02906955
  0.99540122  1.72344809  0.93951838  1.1010409   2.64744965  1.69433779
  3.59158998  1.4

## **#CHI-SQUARE TEST**

In [ ]:
from scipy.stats import chi2_contingency

Data = [[141, 68, 4], [179, 159, 7], [220,216,4], [86,101,4]]
Calculated_ChiSq, p,  Degrees_of_Freedom, Expected_Values = chi2_contingency(Data)

Alpha = 0.05
print("p value is " + str(p))
if p >= Alpha:
    print('Independent (H0 Holds True / We accept the Null Hypothesis)') 
else:
    print('Dependent (We Reject the H0)') 

p value is 0.00044690833914947634
Dependent (We Reject the H0)
